library(dplyr)
library(ggplot2)
library(tidyr)
density <- read.csv("Data/density_estimates.csv")
density[is.na(density)] <- 0
density <- filter(density, Site == "lower")
dens.ag <- aggregate(.~Date, data = density, sum)
dens.ag <- gather(dens.ag, "Shrub", "n", 6:15)
day <- dplyr::select(density, Date, Day)
day <- distinct(day)
dens.ag <- inner_join(dens.ag, day, by = "Date")
dens.ag <- mutate(dens.ag, fl.dens = n/Area)
ggplot(dens.ag, aes(Day.y, fl.dens)) + geom_smooth(model = lm, aes(fill = Shrub)) 
ggplot(dens.ag, aes(Day.y, fl.dens)) + geom_area(aes(fill = Shrub))
